name: Construire APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer Buildozer
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            libncursesw5-dev  cmake \
            libffi-dev libssl-dev
          pip install buildozer cython

      - name: Construire APK
        run: buildozer android debug

      - name: Récupérer APK
        uses: actions/upload-artifact@v4
        with:
          name: calculatrice-pro
          path: bin/*.apk
